# New Methods in Earth Observation



## Tentative Schedule

The following is a schedule for GEOG287-387, which is held in JC105 on Mondays and Wednesdays from 12-13.15 


| Date 	       | Week | Subject                                         | 
|--------------|------|-------------------------------------------------|
| 27 August    | 1 | Course overview / GEOG 391 recap              |
| 29 August    | 1 | What we are going to do              |
| 3 September  | 2 | UAS (field visit 1 of 2 days)           |
| 5 September  | 2 | UAS (field visit 1 of 2 days: PIX4D)    |
| 10 September | 3 | Sensor data (lecture)                   |
| 12 September | 3 | Sensor data (practical: programmatic download / analyze) |
| 17 September | 4 | Planet (lecture)                        |
| 19 September | 4 | Planet data (practical: getting cloud-free data) |
| 24 September | 5 | Big data / EO platforms (lecture)       |
| 26 September | 5 | Big data / EO platforms (practical: Planet/NDVI-LAI) |
| 1 October    | 6 | Active learning (lecture)            |
| 3 October    | 6 | Active learning (practical: toy model example?)    |
| 8 October    | 7 | Fall Break     |
| 10 October   | 7 |                  |
| 15 October   | 8 |                  |
| 17 October   | 8 |                  |
| 22 October   | 9 |                  |
| 24 October   | 9 |                  |
| 29 October)  | 10 |                  |
| 31 October)  | 10 |                  |
| 5 November)  | 11 |                  |
| 7 November)  | 11 |                  |
| 12 November  | 12 |                  |
| 14 November  | 12 |                  |
| 19 November  | 13 |                  |
| 21 November  | 13 | Thanksgiving Recess |
| 26 November  | 14 |                  |
| 28 November  | 14 |                  |
| 3 December   | 15 |                  |
| 5 December   | 15 |                  |
| 10 December  | 16 |                  |
