---
title: "Cloud-based Processing"
subtitle: "New Methods in Earth Observation"
# author: "Lyndon Estes"
date: "10/1/2018"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["default", "lucy", "middlebury-fonts", "themes/class9-theme.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

# Working with: 

## Google Earth Engine
## Radiant Earth

---

## Earth Engine
### [Introduction](https://developers.google.com/earth-engine/)
### [Code Editor](https://developers.google.com/earth-engine/playground)
### [Datasets](https://developers.google.com/earth-engine/datasets/catalog/)
### [Tutorials](https://developers.google.com/earth-engine/tutorials)

---
## Some Basics

### Load and Display an Image

Adapted from the Earth Engine [introductory tutorial](https://developers.google.com/earth-engine/tutorial_api_02).
```{js, eval = FALSE}
// Instantiate an image with the Image constructor.
var srtm = ee.Image('CGIAR/SRTM90_V4');

// Zoom to a location.
Map.setCenter(-112.8598, 36.2841, 9); // Center on the Grand Canyon.

// Display the image on the map.
Map.addLayer(srtm);
```

Let's point somewhere else (substitute this into script)
```{js, eval = FALSE}
Map.setCenter(28, -13, 6); // Where is this?
```

How about here? 
```{js, eval = FALSE}
Map.setCenter(-71.8067, 42.1214, 14); // Where is this?
```

---

Let's add some color
```{js, eval = FALSE}
Map.addLayer(srtm, {min: 0, max: 3000, palette: ['blue', 'green', 'red']},
             'custom palette');
```

---
### Derived Layers
#### Slope and Aspect

Calculate and then have a look 
```{js, eval = FALSE}
// Slope
var slope = ee.Terrain.slope(srtm);

// Aspect
var aspect = ee.Terrain.aspect(srtm);

// Convert to radians, compute the sin of the aspect.
var sinImage = aspect.divide(180).multiply(Math.PI).sin();

// Add these to your displays
Map.addLayer(slope, {min: 0, max :60}, 'slope');
Map.addLayer(aspect, {min: 0, max: 360, palette: ['blue', 'green', 'red']});
Map.addLayer(sinImage, {min: -1, max: 1, palette: ['blue', 'green', 'red']}, 
             'sin');
```

---
### Image Statistics
#### First, define an area of interest
&nbsp;&nbsp;1. Use the polygon tool to draw a polygon, which you rename to "myaoi"

&nbsp;&nbsp;2. Turn an extent into a geometry feature
```{js, eval = FALSE}
// Clip boundaries (generous margin around Zambia)
var zam = ee.Feature(ee.Geometry.Rectangle(21, -19, 34.5, -7.5));
```

&nbsp;&nbsp;3. Use an existing feature collection
```{js, eval = FALSE}
// Load a region representing Zambia
var region = ee.Feature(
  ee.FeatureCollection('ft:1tdSwUL7MVpOauSgRzqVTOwdfy17KDbw-1d9omPw')
  .filterMetadata('Country', 'equals', 'Zambia')
  .first());
```

Or:
```{js, eval = FALSE}
var region = ee.Feature(
  ee.FeatureCollection("USDOS/LSIB/2013")
  .filterMetadata('cc', 'equals', 'ZA')
  .first());
```

---

#### Calculate summary statistics within the AOI
```{js, eval = FALSE}
// Mean elevation
var meanDict = srtm.reduceRegion({
  reducer: ee.Reducer.mean(),
  geometry: myaoi,
  scale: 90,
  maxPixels: 1e8
  //bestEffort: true
});

// Get the mean from the dictionary and print it.
var mean = meanDict.get('elevation');
print('Mean elevation', mean);
```

---
## Image Collections

Landsat 8
```{js, eval = FALSE}
var l8 = ee.ImageCollection('LANDSAT/LC08/C01/T1_TOA');

var spatialFiltered = l8.filterBounds(myaoi);
print('spatialFiltered', spatialFiltered);

var temporalFiltered = spatialFiltered.filterDate('2018-05-01', '2018-09-15');
print('temporalFiltered', temporalFiltered);
```

Find least cloudy
```{js, eval = FALSE}
// Sort from least to most cloudy.
var sorted = temporalFiltered.sort('CLOUD_COVER');

// Get least cloudy image
var scene = ee.Image(sorted.first());
```

Display. Run this then try make a false color. 
```{js, eval = FALSE}
var visParams = {bands: ['B4', 'B3', 'B2'], max: 0.3};
//var visParams = {bands: ['B5', 'B4', 'B3'], max: 0.3};
Map.addLayer(scene, visParams, 'true-color composite');
```

---
Show a collection
```{js, eval = FALSE}
var visParams = {bands: ['B4', 'B3', 'B2'], max: 0.3};
Map.addLayer(temporalFiltered, visParams, 'Whittier L8 collection');
```

### Compositing

```{js, eval = FALSE}
var median = temporalFiltered.median();
Map.addLayer(median, visParams, 'Whittier L8 collection');
```

### Cropping
```{js, eval = FALSE}
var whittier_median = median.clip(myaoi);
```

### Masking
```{js, eval = FALSE}
var elevmask = srtm.gt(100);
var maskedMedian = median.updateMask(elevmask);
```

---
## Calculating NDVI over a collection
```{js, eval = FALSE}
var addNDVI = function(image) {
  var ndvi = image.normalizedDifference(['B5', 'B4']).rename('NDVI');
  return image.addBands(ndvi);
};

// Apply function to single image
var ndvi = addNDVI(image).select('NDVI');

// Map onto a collection
var withNDVI = temporalFiltered.map(addNDVI);
```

---

## Charts
```{js, eval = FALSE}
// Create chart
var chart = ui.Chart.image.series({
  imageCollection: withNDVI.select('NDVI'),
  region: myaoi,
  reducer: ee.Reducer.first(),
  scale: 30
}).setOptions({title: 'NDVI over time'});

// Display the chart in the console.
print(chart);

```

---

# Homework 

The scripts we used today, plus some more advanced ones, are provided [here](https://github.com/agroimpacts/geog287387/blob/master/materials/code/javascript/earthengine.md). You may find these helpful in undertaking the homework. 

## Earth Engine 1
Adapt the Landsat code as follows: 

&nbsp;&nbsp;- Replace Landsat 8 TOA with the Tier 1 surface reflectance collection

&nbsp;&nbsp;- Calculate GCVI instead of NDVI, using this function: 

```{js, eval = FALSE}
var addGCVI = function(image){
  gcvi = image.expression(
    '(NIR / GREEN) - 1.0', {
    'NIR': image.select('B5'),
    'GREEN': image.select('B3')
    }).rename('GCVI');
  return(image.addBands(gcvi))    
}
```

---

## Earth Engine 2
&nbsp;&nbsp;- Upload the full Planet scenes (unclipped) you downloaded

&nbsp;&nbsp;- Upload the PPK non-target reflectance drone image

&nbsp;&nbsp;- You will ingest these as image assets.


## Radiant Earth
&nbsp;&nbsp;- Follow this [tutorial](https://help.radiant.earth/basic-resource-guide/creating-projects/create-a-standard-project-and-add-available-imagery) to create your first project

&nbsp;&nbsp;- Zoom in to level 9 over Sutton, MA

&nbsp;&nbsp;- Select all Sentinel 2 scenes that: 

&nbsp;&nbsp;&nbsp;&nbsp;+ Totally cover that location; 

&nbsp;&nbsp;&nbsp;&nbsp;+ Falling within the period May 1, 2018 - September 15, 2018;

&nbsp;&nbsp;&nbsp;&nbsp;+ Have cloud cover <10%. 

&nbsp;&nbsp;&nbsp;&nbsp;+ [These instructions will help](https://help.radiant.earth/basic-resource-guide/creating-projects/how-to-find-the-right-image)

Note that these scenes will show up as not yet ingested, so will take a while to show up in your project. 

