---
title: "Realtime In Situ Sensing"
subtitle: "New Methods in Earth Observation"
# author: "Lyndon Estes"
date: "10/3/2018"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["default", "lucy", "middlebury-fonts", "themes/class11-theme.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---




```{r, eval = TRUE, echo = FALSE, warning = FALSE, message = FALSE}
library(leaflet)
library(sf)
library(dplyr)

xs <- c(-71.806965, -71.806478, -71.805491)
ys <- c(42.120884, 42.121805, 42.122951)

pts <- st_sfc(st_multipoint(cbind(x = as.numeric(xs), y = as.numeric(ys))))

planet1 <- paste0("https://tiles.rasterfoundry.com/", 
                  "7a4b4cb3-fe35-46c9-9896-6e98eec46665/{z}/{x}/{y}/?tag=",
                  "1538578249206&mapToken=8ab506f7-9ef0-46f2-afe6-db5ec1c9e9e4")
planet2 <- paste0("https://tiles.rasterfoundry.com/",
                  "43ebd5c0-ae71-4505-8ab5-e1009583d0be/{z}/{x}/{y}/?tag=",
                  "1538578546868&mapToken=93ccd998-413a-458c-a573-ffa7e49ca251")
sequoia <- paste0("https://tiles.rasterfoundry.com/", 
                  "e319cae9-4093-40b1-8961-033fa6753ec6/{z}/{x}/{y}/?tag=",
                  "1538580563314&mapToken=3438e35f-07d3-4644-a52a-aea0a4bf7aec")

m <- leaflet() %>% addProviderTiles("Esri.WorldImagery") %>% 
  setView(xs[1], ys[2], zoom = 15) %>%
  addTiles(planet1, group = "planet6/12") %>% 
  addTiles(sequoia, group = "planet6/16") %>% 
  addMarkers(lng = as.numeric(xs), lat = as.numeric(ys)) %>% 
  addLayersControl(overlayGroups = c("sequoia", "planet6/16"),
                   options = layersControlOptions(collapsed = FALSE, 
                                                  autoZIndex = FALSE))
m
```

---

```{r, echo = FALSE, message=FALSE, warning=FALSE}
library(data.table)
load(file.path("~/Dropbox/projects/yld/external/data/", 
               "whittier_hourly_08062018-06092018.rda"))
datsdt <- lapply(dats, data.table)
par(mfrow = c(3, 1), mar = c(3, 3, 1, 0), oma = c(3, 3, 0, 0))
cols = c("purple", "orange", "blue")
axesplot = c("n", "n", "s")
for(i in 1:3) {
  datsdt[[i]][, plot(time, PARdw, type = "l", col = cols[i], xlab = "date", 
                     ylab = "PAR", xaxt = axesplot[i], las = 2)]
} 

```

---

# Introducing Dr. Adam Wolf
