---
title: "Cloud-based Processed => Realtime In Situ Sensing"
subtitle: "New Methods in Earth Observation"
# author: "Lyndon Estes"
date: "10/3/2018"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["default", "lucy", "middlebury-fonts", "themes/class11-theme.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: center, middle

# Cloud Processing Practicals/Homework
## Wrap-up

---
## Earth Engine 
### 1. GCVI on Landsat

[Code](https://code.earthengine.google.com/21f7df3222b920bc725ab242c729ec37)

### 2. Upload Planet and UAS imagery

### 3. Planet ImageCollection and GCVI

[Code](https://code.earthengine.google.com/21f7df3222b920bc725ab242c729ec37)

---
## Radiant Earth
[Login](https://app.radiant.earth)


---
## Working with Arable Mark data

Get the `aRable` R package .tgz from Slack

```{r, eval=FALSE}
# install.packages("devtools")  # if you don't already have it
library(devtools)
library(data.table)
install.packages("~/Dropbox/projects/aRable_0.1.1.tgz", repos = NULL)

# our device IDs
devices <- c("A000667", "A000671", "A000680")

# let's get some daily data for A000667
?ArableClient
dev1 <- ArableClient(device = devices[1], measure = "daily",
                     start = "2018-06-01", end = "2018-06-30",
                     email = "lestes@clarku.edu", password = "rollinghills88",
                     tenant = "clark")
```

---

## Let's take a look at the data

```{r, eval = FALSE}
dev1 <- data.table(dev1)
dev1[is.na(precip), precip := 0]
par(mfrow = c(2, 2), mgp = c(2, 0.25, 0), tcl = -0.1, las = 2, 
    mar = c(3, 3, 0.5, 0), lwd = 2)
dev1[, plot(datetime, precip, type = "l", col = "blue", xlab = "")]
dev1[, plot(datetime, NDVI, type = "l", col = "green3", xlab = "")]
dev1[plot(datetime, meanT, type = "l", col = "purple", xlab = "")]
dev1[plot(datetime, CGDD, type = "l", col = "orange", xlab = "")]

```














