---
title: "Droning On 2"
subtitle: "New Methods in Earth Observation"
author: "Lyndon Estes"
date: "9/4/2018"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["default", "lucy", "middlebury-fonts", "my-theme2.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: center, middle

# Collecting Data

---

### Plan mission eMotion3
#### Select plane, altitude, camera characteristics
--

#### Examine wind

--

#### Set home and start point

--

#### Add landing sectors

--

#### Create a mission block

---

### Post-mission
#### Transfer photos from camera to computer

--

#### Transfer flight logs from drone to computer

---

### Post-processing for PPK corrections
#### Got to post-flight section of eMotion3, create new project

--

#### Load in drone flight logs

--

#### Collect and load in RINEX file from: https://www.ngs.noaa.gov/UFCORS/

--

#### Complete post-processing steps

---
class: center, middle

# Image Mosaicking

---
### Open PIX4D
#### Create new project

--

#### Add images (msp from eMotion3 post-processed folder)

--

#### Choose processing options template (Ag Multispectral)

--

#### Choose post-processing options 
##### *1. Initial processing (camera alignment)*
##### *2. Point cloud and mesh*
##### *3. DSM, orthomosaic, and index*

---

### View Results!

#### Ray Cloud

--

#### Quality Report

--

#### Orthos and DSM

---
class: center, middle

# Homework

---

### 5 Processing tasks
#### 24 August images PPK/RTK + reflectance target (started in-class)
#### 24 August images PPK/RTK + no reflectance target
#### 24 August images no PPK/RTK + no reflectance target
#### 31 August images PPK/RTK + no reflectance target
#### 31 August images PPK/RTK + reflectance target

### We will analyze differences next class!


